### ISSUE TITLE
Multisite access

### ISSUE THREAD

**Issue by nineplanets** [alfreddatakillen/stop-xmlrpc-attack#1]
Great plugin. Can you add some code so that this will show up in the multisite admin for super admins?

**Comment by alfreddatakillen** [comment]
Hello! It does in my multi site installs. I believe we need some more debug info on this issue...

**Comment by alfreddatakillen** [comment]
If you are still running version 1.0.0, that is a bug. However, it should work in the latest releaste 1.0.3.

**Comment by nineplanets** [comment]
Perfect, got it working. Thanks!
